### PR TITLE
Adds !players command for discord and /players for ingame.

### PR DESCRIPTION
**Pull request by olliy1or**

### CODE REVIEW

**Comment by moreavy** [comment]
@olliy1or The `/status` command tells us the number of online players. I don't think we need `/players`.

**Comment by BrownHedgehog78** [comment]
Also there's /who command. Please fix the Luacheck

**Review by Panquesito7 — COMMENTED** [review]
Please fix [LuaCheck](https://github.com/MT-CTF/servermods/runs/1594523636) warnings.
Also, it would be cool if it could tell you the number of online players, e.g.:

```
Connected players (10): olliy, Panquesito7, ...
```
But you should probably override the `status` command instead of making multiple commands (not sure if it's a good idea though).

**Comment by BrownHedgehog78** [comment]
There's /who, it shows player number and name.

**Pull request closed without merging**
