### PR TITLE
Don't add gauges if fly = true, interact = false

### PR DESCRIPTION
**Pull request by ClobberXD**

### CODE REVIEW

**Comment by rubenwardy** [comment]
```lua
local privs = minetest.get_player_privs(name)
if privs.interact or not privs.fly then
 		old_add_gauge(name) 
end
```

**Comment by rubenwardy** [comment]
Should be or - players may join without interact because they haven't accepted the rules

**Comment by rubenwardy** [comment]
Note that the old condition was this:

```lua
not (privs.fly and not privs.interact)
```

The not is because the stuff inside the brackets would exit the function early, so it needs to not be true for the old_set to run.

If you expand this out you get this:

```lua
not (privs.fly and not privs.interact)
=>  not privs.fly or privs.interact
```

This is from the logical rule:  `not (a and b) == not a or not b`

So making it `or` as in my suggest is equivalent to the old behaviour

**Comment by ClobberXD** [comment]
Makes sense; thanks for explaining.

**Pull request merged**
